try
{
    source.Execute(scope);
}
catch (Exception ex)
{
    MessageBox.Show("오류가 발생했습니다: " + ex.Message);
}
